apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-test
  labels:
    app: spring-petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-petclinic
    spec:
      containers:
      - name: spring-petclinic
        image: aisuluu3008/spring-petclinic
        ports:
        - containerPort: 80
