apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-test
  labels:
    app: gke-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gke-test
  template:
    metadata:
      labels:
        app: gke-test
    spec:
      containers:
      - name: spring-petclinic
        image: aisuluu3008/spring-petclinic
        ports:
        - containerPort: 80
