apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-test
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-petclinic
    spec:
      containers:
      - name: spring-petclinic
        image: aisuluu3008/spring-petclinic
        ports:
        - containerPort: 80
