apiVersion: v1
kind: Service
metadata:
  name: product-zero-svc
spec:
  selector:
    app: product-zero-spring-petclinic
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http
